### PR TITLE
fix: prevent closing the active view when clicking on a disabled hour/minute

### LINKED ISSUE #158: Min date disabling hour pickers on twelve-hour time
When the datetimepicker is using [twelvehour]="true", setting a [min] value on the corresponding input field causes the hour picker to misbehave. All hours are disabled, and if the user clicks on an hour, they are moved to the minute picker where, when a minute is selected, the day of the date picked changes to the following day. This does not occur when [twelvehour] is set to false or not set.

I should mention this is when using the native date adapter.

### PR DESCRIPTION
**Pull request by Waseem-Isaac**
A click on a disabled item should do nothing.
these changes fixes an issue with me, And I think it will fix https://github.com/kuhnroyal/mat-datetimepicker/issues/158 as well.

### CODE REVIEW

File: projects/core/src/datetimepicker/clock.ts [hunk 1]
```diff
@@ -338,6 +338,11 @@ export class MatDatetimepickerClockComponent<D> implements AfterContentInit {
           ? 0
           : value + 12;
       }
+
+      // Don't close the hours view if an invalid hour is clicked.
+      if (!this._hours.find((h) => h?.['value'] === value)?.['enabled']) {
+        return;
+      }
```
Comment (bbortt) [inline projects/core/src/datetimepicker/clock.ts:345]: I'd add a newline here ;)

File: projects/core/src/datetimepicker/clock.ts [hunk 2]
```diff
@@ -352,6 +357,11 @@ export class MatDatetimepickerClockComponent<D> implements AfterContentInit {
       if (value === 60) {
         value = 0;
       }
+
+      // Don't close the minutes view if an invalid minute is clicked.
+      if (!this._minutes.find((m) => m?.['value'] === value)?.['enabled']) {
+        return;
+      }
```
Comment (bbortt) [inline projects/core/src/datetimepicker/clock.ts:365]: and here as well.

**Review by bbortt — CHANGES_REQUESTED** [review]
thx very much! I think this is rather a fix, than a feature, right? so I'd type the commit as `fix(#158):`.
and since you will have to amend the commit, I also left two small lints I'd correct.

**Comment by Waseem-Isaac** [comment]
> thx very much! I think this is rather a fix, than a feature, right? so I'd type the commit as `fix(#158):`. and since you will have to amend the commit, I also left two small lints I'd correct.

I agree, Honestly I noticed  #158 after I added my fix :), I made it for another issue appeared with me.

**Review by bbortt — APPROVED** [review]
thank you :)
